### ISSUE TITLE
Update for Cataclysm Classic?

### ISSUE THREAD

**Issue by sausje** [doneykoo/xmerchant-wow-addon#10]
As of right now it's not even showing in the addon list. I presume because there's no .toc for cata included?

Do you have plans to make this work for cata or should we start looking for alternatives? Thanks.

**Comment by doneykoo** [comment]
I think you are right. Need an update


Regards,


sausje ***@***.***>于2024年5月25日 周六18:36写道：

**Comment by doneykoo** [comment]
updated, have a try

Regards,
