### ISSUE TITLE
Clicking on the "Search in Tooltips" **checkbox** (next to the search field), triggers an error.

### ISSUE THREAD

**Issue by xan2622** [doneykoo/xmerchant-wow-addon#2]
**Describe the bug**
Clicking on the "Search in Tooltips" **checkbox** (next to the search field), triggers an error.

**Steps to reproduce the behavior:**
1. Start trading with a PNJ.
2. Click on the "Search In Tooltips" checkbox
3. See error

**Expected behavior**
The addon does tick the checkbox but it also displays a Lua error (it would be nice not to see this error).

**Screenshots**

![error_xMerchant](https://user-images.githubusercontent.com/1732773/113579593-d0bd7b80-9624-11eb-9de2-24e039cfa1cd.jpg)

**Version:**
 - World of Warcraft (official): 9.0.5.38134
 - Server locale region: FR
 - OS: Windows 10 64bits
 
**The error:**
```
Message: Interface\AddOns\xMerchant\core.lua:809: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Time: Mon Apr  5 15:39:48 2021
Count: 1
Stack: Interface\AddOns\xMerchant\core.lua:809: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[string "=[C]"]: in function `PlaySound'
[string "@Interface\AddOns\xMerchant\core.lua"]:809: in function <Interface\AddOns\xMerchant\core.lua:807>

Locals: (*temporary) = "igMainMenuOptionCheckBoxOn"

```

**Comment by doneykoo** [comment]
Released on Curse: `1.9.4-release`
