### ISSUE TITLE
Wrath 3.4.1 broken

### ISSUE THREAD

**Issue by sausje** [doneykoo/xmerchant-wow-addon#6]
1x xMerchant/core.lua:459: attempt to index local 'button' (a nil value)
[string "@xMerchant/core.lua"]:459: in function <xMerchant/core.lua:438>
[string "@xMerchant/core.lua"]:752: in function <xMerchant/core.lua:750>

Locals:
self = NuuhMerchantFrame {
 top = NuuhMerchantFrameTop {
 }
 search = NuuhMerchantFrameSearch {
 }
 bottom = NuuhMerchantFrameBottom {
 }
 scrollframe = NuuhMerchantScrollFrame {
 }
 0 = <userdata>
}
numMerchantItems = 8
(for index) = 1
(for limit) = 10
(for step) = 1
i = 1
offset = 1
button = nil
(*temporary) = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 1
(*temporary) = NuuhMerchantScrollFrameScrollBar {
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 ThumbTexture = NuuhMerchantScrollFrameScrollBarThumbTexture {
 }
 Center = Texture {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 BottomEdge = Texture {
 }
 LeftEdge = Texture {
 }
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 TopLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 ScrollDownButton = NuuhMerchantScrollFrameScrollBarScrollDownButton {
 }
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 backdropInfo = <table> {
 }
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 ScrollUpButton = NuuhMerchantScrollFrameScrollBarScrollUpButton {
 }
 0 = <userdata>
}
(*temporary) = NuuhMerchantScrollFrameScrollChildFrame {
 0 = <userdata>
}
(*temporary) = NuuhMerchantScrollFrameScrollBarScrollUpButton {
 0 = <userdata>
 Pushed = Texture {
 }
 Disabled = Texture {
 }
 Highlight = Texture {
 }
 Normal = Texture {
 }
}
(*temporary) = NuuhMerchantScrollFrameScrollBarScrollDownButton {
 0 = <userdata>
 Pushed = Texture {
 }
 Disabled = Texture {
 }
 Highlight = Texture {
 }
 Normal = Texture {
 }
}
(*temporary) = 1
(*temporary) = 0
(*temporary) = 235.200000
(*temporary) = 0
(*temporary) = <function> defined =[C]:-1
(*temporary) = NuuhMerchantScrollFrameScrollBarScrollDownButton {
 0 = <userdata>
 Pushed = Texture {
 }
 Disabled = Texture {
 }
 Highlight = Texture {
 }
 Normal = Texture {
 }
}
(*temporary) = <userdata>
(*temporary) = <userdata>
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'button' (a nil value)"
XMERCHANT_LOGD = <function> defined @xMerchant/core.lua:68
xMerchant = <table> {
 applyOptions = <function> defined @xMerchant/config.lua:56
 merchantFrame = NuuhMerchantFrame {
 }
 getCurrentDB = <function> defined @xMerchant/core.lua:44
 merchantFrameButtons = <table> {
 }
 resetCurrentDB = <function> defined @xMerchant/config.lua:44
 initDB = <function> defined @xMerchant/config.lua:28
 LOGW = <function> defined @xMerchant/core.lua:80
 L = <table> {
 }
 OptionsFrame = xMerchantOptions {
 }
 kItemButtonHeight = 29.400000
}
buttons = <table> {
}
searching = "search"
tooltip = NuuhMerchantTooltip {
 SetBorderBlendMode = <function> defined @SharedXML/SharedTooltipTemplates.lua:203
 NineSlice = Frame {
 }
 updateTooltip = 0.200000
 TooltipBackdropOnLoad = <function> defined @SharedXML/SharedTooltipTemplates

**Comment by ZythDr** [comment]
Same issue here, months later :(

**Comment by doneykoo** [comment]
released: 1.10.2-release-wotlk
