### ISSUE TITLE
Lua error when have two gear in different ilvl in the bag.

### ISSUE THREAD

**Issue by TaikooS** [doneykoo/xmerchant-wow-addon#9]
**Describe the bug**
As mentioned in the title.

**To Reproduce**
Have gears with the same name, e.g. Tier set piece in LFR and Normal, etc.

**Version:**
 - wow retail 10.1.5
 - Server locale region: TW
 - OS: Windows 10

**Additional context**

2x xMerchant/core.lua:299: attempt to perform arithmetic on local 'count' (a nil value)
[string "@xMerchant/core.lua"]:299: in function <xMerchant/core.lua:256>
[string "@xMerchant/core.lua"]:1054: in function <xMerchant/core.lua:1047>
[string "=[C]"]: in function `MerchantFrame_Update'
[string "@FrameXML/MerchantFrame.lua"]:50: in function <FrameXML/MerchantFrame.lua:42>

Locals:
limit = 74
(for index) = 2
(for limit) = 4
(for step) = 1
bagID = 2
numSlots = 32
(for index) = 14
(for limit) = 32
(for step) = 1
slotID = 14
itemID = 202543
count = nil
currency = 1
(*temporary) = <table> {
 192999 = 1
 202540 = 1
 193809 = 1
 202541 = 1
 殘留的靈魂碎片 = 0
 奇特的硬幣 = 136
 202542 = 1
 鬥陣金幣 = 1196
 上古法力 = 932
 宇宙靈流 = 94398
 灌能紅寶石 = 100
 商人的標幣 = 975
 時朽文物 = 0
 腐化死亡之翼的精華 = 0
 204211 = 1
 文物碎片 = 0
 198322 = 1
 黑暗微粒 = 0
 大廳資源 = 57040
 龍石 = 2000
 油料 = 185
 銀白十字軍表揚令 = 124
 勇士徽印 = 39
 高塔知識 = 0
 194879 = 1
 193768 = 1
 200642 = 1
 風暴符印 = 30
 血腥硬幣 = 1154
 朦朧的阿古岩 = 2000
 要塞資源 = 10000
 193738 = 1
 首創者的暗語 = 1997
 感激禮賜 = 409
 元素溢流 = 102019
 宿命徽印 = 6
 頂尖水晶 = 125636
 征服點數 = 0
 超因果薄片 = 4805
 覺醒精華 = 930
 破碎命運徽印 = 0
 榮勛軍團軍功獎章 = 566
 盲目之眼 = 889
 151116 = 1
 202573 = 1
 冥魄 = 11263
 永恆硬幣 = 85522
 202543 = 1
 次級好運符咒 = 276
 美食主義者的獎勵 = 38
 193519 = 1
 罪孽石碎片 = 15623
 榮譽點數 = 3
 冥魄餘燼 = 107
 腐化的紀念物 = 17184
 海員古幣 = 114
 聚合幻象 = 306372
 托巴拉德表揚徽章 = 18
 暗月獎品券 = 976
 軍團之殞戰爭物資 = 588
 63378 = 1
 稜光法力珍珠 = 826
 巨龍群島補給品 = 29881
 戰亂命運徽印 = 3
 戰爭物資 = 78637
 世界之樹印記 = 28
 奈奧羅薩回音 = 35960
 虛空裂片 = 38273
 靈魂燼火 = 5536
 編目研究 = 30349
 鐵爪徽章 = 255
 靈魂灰燼 = 41736
 長者的好運符咒 = 0
 時光扭曲徽章 = 25
 202539 = 1
 淬鍊命運徽印 = 2
 193773 = 1
 泰坦殘質 = 0
 魔古的命運符文 = 4
 庫存靈魄 = 56726
 戰鑄徽印 = 0
}
(*temporary) = 202543
(*temporary) = 2
(*temporary) = "attempt to perform arithmetic on local 'count' (a nil value)"
currencies = <table> {
 192999 = 1
 202540 = 1
 193809 = 1
 202541 = 1
 殘留的靈魂碎片 = 0
 奇特的硬幣 = 136
 202542 = 1
 鬥陣金幣 = 1196
 上古法力 = 932
 宇宙靈流 = 94398
 灌能紅寶石 = 100
 商人的標幣 = 975
 時朽文物 = 0
 腐化死亡之翼的精華 = 0
 204211 = 1
 文物碎片 = 0
 198322 = 1
 黑暗微粒 = 0
 大廳資源 = 57040
 龍石 = 2000
 油料 = 185
 銀白十字軍表揚令 = 124
 勇士徽印 = 39
 高塔知識 = 0
 194879 = 1
 193768 = 1
 200642 = 1
 風暴符印 = 30
 血腥硬幣 = 1154
 朦朧的阿古岩 = 2000
 要塞資源 = 10000
 193738 = 1
 首創者的暗語 = 1997
 感激禮賜 = 409
 元素溢流 = 102019
 宿命徽印 = 6
 頂尖水晶 = 125636
 征服點數 = 0
 超因果薄片 = 4805
 覺醒精華 = 930
 破碎命運徽印 = 0
 榮勛軍團軍功獎章 = 566
 盲目之眼 = 889
 151116 = 1
 202573 = 1
 冥魄 = 11263
 永恆硬幣 = 85522
 202543 = 1
 次級好運符咒 = 276
 美食主義者的獎勵 = 38
 193519 = 1
 罪孽石碎片 = 15623
 榮譽點數 = 3
 冥魄餘燼 = 107
 腐化的紀念物 = 17184
 海員古幣 = 114
 聚合幻象 = 306372
 托巴拉德表揚徽章 = 18
 暗月獎品券 = 976
 軍團之殞戰爭物資 = 588
 63378 = 1
 稜光法力珍珠 = 826
 巨龍群島補給品 = 29881
 戰亂命運徽印 = 3
 戰爭物資 = 78637
 世界之樹印記 = 28
 奈奧羅薩回音 = 35960
 虛空裂片 = 38273
 靈魂燼火 = 5536
 編目研究 = 30349
 鐵爪徽章 = 255
 靈魂灰燼 = 41736
 長者的好運符咒 = 0
 時光扭曲徽章 = 25
 202539 = 1
 淬鍊命運徽印 = 2
 193773 = 1
 泰坦殘質 = 0
 魔古的命運符文 = 4
 庫存靈魄 = 56726
 戰鑄徽印 = 0
}
XMERCHANT_LOGD = <function> defined @xMerchant/core.lua:78
XMERCHANT_DEBUG_TAGS = <table> {
 [Faction] = 0
 [AltCurrency] = 0
 [CurrencyUpdate] = 0
 [CurrencyFrames] = 0
 CurrencyUpdate = 0
 [MerchantItemInfo] = 0
 [GetKnown] = 0
 [GetError] = 0
 [FactionsUpdate] = 0
}
GetContainerNumSlots = <function> defined =[C]:-1
GetContainerItemID = <function> defined =[C]:-1
GetContainerItemInfo = <function> defined

**Comment by sausje** [comment]
Yeah same here

**Comment by doneykoo** [comment]
I've made a fix and pushed a new version: `1.10.4`.
Would you kindly help to test it? @TaikooS , @sausje ?

**Comment by TaikooS** [comment]
Sorry for the late reply.
It works well now, thank you for the update!
